### ISSUE TITLE
Suggestion to preserve ThePrimeagen's time and sanity

### ISSUE THREAD

**Issue by novusnota** [ThePrimeagen/ts-rust-zig-deez#114]
Ok, so maintaining this repo with all the PRs gets really unwieldy even with people slowly getting on CODEOWNERS file.

Hence, I propose a solution — to split the repo in two:
1. ThePrimeagen & TJ will continue to work here on Rust, Zig, TS and OCaml
2. Degen legion and all language implementations will move to a different, community-maintained repo

This way Prime won't have to take care of maintaining anything but his own good stuff :)
Therefore, less management and more excitement towards coding!

@ThePrimeagen if you agree, pls, send here the list of people selected on Monday stream. I'll organize the rest.

**Comment by Fa-C-Shus** [comment]
Has anyone chosen to implement in MonkeyLang? dibs!!!

**Comment by novusnota** [comment]
@ThePrimeagen that's precisely why I'm doing this! Ok, here is the fork: https://github.com/novusnota/monkey-deez
Give me a moment, I'll merge PRs into it.

**Comment by ThePrimeagen** [comment]
wait... what? i am now getting my time in today to review things.

i like this idea of a fork that has all the other languages and this one having one.

that is pretty dang confusing.  i would rather just work on one and this one specifically.

**Comment by ThePrimeagen** [comment]
ok, sorry that this is public

not supporting monkey-deez

closing down issue.  trying to go through prs now, will try to make it to about ~10-20 PRs a day, would like some help though if anyone is willing to offer some
