### ISSUE TITLE
C++ code questions

### ISSUE THREAD

**Issue by GFORW** [ThePrimeagen/ts-rust-zig-deez#180]
~~ Hi,  whats up with that `Iterator>=container.end()` stuff, why check for `>=`, it is not supposed to work like pointers, it just gives you std::end,  if you iterated to the ater the end or in case of not finding value by comparator, as i undestand, please correct me if i am wrong. ([source](https://en.cppreference.com/w/cpp/iterator/end))~~ 
nvm i am blind

**Comment by Spongman** [comment]
it's a valid question. in theory `==` is sufficient, but `>=` is more defentive. if for whatever reason the iterator skips from `<= end()` to `>= end()` then the `==` results in an infinite loop (well, until after `size_t` overflows). it "can't" happen here. until it does....
