### ISSUE TITLE
JDSL, not sure how to include

### ISSUE THREAD

**Issue by AlexanderBrevig** [ThePrimeagen/ts-rust-zig-deez#209]
Hi! Amazing project to watch :D 

I've made https://github.com/AlexanderBrevig/JDSL but since it's heavily dependent on commit history it will be a chore to add it.
Would it be possible to not squash the PR if I get around to it? :) 

You all rock!

**Comment by Crain-32** [comment]
Smh not using the superior [JJDSL](https://github.com/ThePrimeagen/ts-rust-zig-deez/tree/master/jjdsl). But otherwise a great job.
