### ISSUE TITLE
Hosted on Linode?

### ISSUE THREAD

**Issue by eratio08** [ThePrimeagen/ts-rust-zig-deez#94]
Will the interpreters run on Linode? We could provide a terraform setup to make it IoC and easy.

**Comment by ThePrimeagen** [comment]
so a big thing for me is i am not a dev ops guy

so whatever i can accomplish the following the easiest with
1. on linode because i have some free credits left
2. i can spawn testing clients (likely node because i want to try drizzle)
3. i can spawn test servers
4. each test server will get X amount of client nodes


side note, i'll use turso to store requesting data so therefore it will be easy to orchestrate the memory

**Comment by eratio08** [comment]
So linode has an [official terraform provider](https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance), this means this can be done via terraform in a declarative way (or even imperative if you want to use the terraform cloud developent kit aka terraform CDK). 
Using IoC here will make it very easy to create linode instances by just coping the configuration as code (there are also other ways with terraform but that would be the simplest).

I did not yet work with linode but I have some xp using terraform with AWS. I will try to prep some example setup. 

If you already have some setup in linode this can also be moved into terraform by importing it.

I'm assuming only you will do any changes to linode which will make the question where to store the terraform state also easy, as it could just be stored local on you machine. For distributed working the state would be to be stored on a dedicated storage like s3.

I will try to prepp something 🔍

**Comment by eratio08** [comment]
So I would assume a single instance per server and some instance running multiple clients. The provisioning of the instances could be done via terraform and simple linode node. Such a setup has the downside that running the actual server would still require some scripting to prepare the node and get the code into the node.

Another approach could be to use LKE (this is the linode managed K8s). This setup is way more complicated but would make it very simple for you to spin up server and clients. You would just need to write K8s Deployment manifest and other manifest. You would also need to have a container registry to which all images are pushed and then pulled by K8s.

The simple instance setup could be helped using ansible but I guess we would need some ansible expert to prepp that.
